# TODO: later change tag by input variable ${{ inputs.tag }}
name: Publish main packages 16
on:
  workflow_dispatch:
  workflow_call:
env:
  npmrc_config_push: ${{ secrets.NPMRC_CONFIG_PUSH }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_PUBLISH_TOKEN }}
permissions:
  contents: read
  packages: write
jobs:
  v3_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node_modules_ng_16-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules_ng_16-

      - name: 'Initial changes 16'
        run: |
          cp -f package.json.ng16 package.json
          cp -f package-lock.json.ng16 package-lock.json

      - name: Install dependencies
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts

      - name: Save cache...
        id: cache-save
        uses: actions/cache/save@v3
        if: ${{ steps.cache-restore.outputs.cache-hit != 'true' && always() }}
        with:
          path: ./node_modules
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

      - name: 'Increase max memory limit'
        run: |
          export NODE_OPTIONS="--max_old_space_size=4096"

      - name: Set up environment variables
        run: |
          last_v3_version=$(
            npm view @prizm-ui/components versions --json | jq '([.[] | select(startswith("3.3.0"))] | last // "3.3.0")' 2>/dev/null || echo '3.3.0'
          )
          echo "LAST_V3_VERSION=${last_v3_version}" >> $GITHUB_ENV

      - name: 'Set version 16'
        run: npx nx generate @prizm-ui/nx-mv:apply -n v16

      #      - name: 'Update v3 versions'
      #        run: npx nx generate @prizm-ui/nx-plugin:update-version --updateInDependencies true --newVersion="3.*.*-v3.up" --all --currentVersion="${{ env.LAST_V3_VERSION }}"

      - name: 'Build v3 versions'
        run: npx nx run-many --target=build --all --parallel --max-parallel=3

      - run: cd dist/libs/components && npm publish --access public --verbose || exit_code=0
      - run: cd dist/libs/i18n && npm publish --access public --verbose || exit_code=0
      - run: cd dist/libs/helpers && npm publish --access public --verbose || exit_code=0
      - run: cd dist/libs/core && npm publish --access public --verbose || exit_code=0
      - run: cd dist/libs/theme && npm publish --access public --verbose || exit_code=0
      - run: cd dist/libs/icons/base && npm publish --access public --verbose || exit_code=0
      - run: cd dist/libs/icons/flags && npm publish --access public --verbose || exit_code=0
      - run: cd dist/libs/plugin && npm publish --access public --verbose || exit_code=0
      - run: cd dist/libs/ast && npm publish --access public --verbose || exit_code=0
      - run: cd dist/libs/charts && npm publish --access public --verbose || exit_code=0
      - run: cd dist/libs/nxmv && npm publish --access public --verbose || exit_code=0

      - name: 'Build doc app for firebase hosting'
        run: npm run build:doc

      - name: Deploy doc to firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRIZMUI }}'
          projectId: prizmui
          channelId: live
          target: v3

      - name: Deploy doc to firebase (LATEST)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRIZMUI }}'
          projectId: prizmui
          channelId: live
          target: main
